name: Trigger auto deployment for album-backend-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/album-backend-api-AutoDeployTrigger-9811a274-02cb-47b2-bed0-e7bc637e1c30.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ALBUMBACKENDAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ALBUMBACKENDAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ALBUMBACKENDAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 21012526.azurecr.io
          registryUsername: ${{ secrets.ALBUMBACKENDAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ALBUMBACKENDAPI_REGISTRY_PASSWORD }}
          containerAppName: album-backend-api
          resourceGroup: rg-containerapps-github-actions
          imageToBuild: 21012526.azurecr.io/album-backend-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


